import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "FinalPing Privacy Policy. How we collect, use, and protect your data.",
};

export default function PrivacyPage() {
  return (
    <div style={{ maxWidth: "760px", margin: "0 auto", padding: "60px 24px 80px" }}>
      <h1 style={{ fontSize: "32px", fontWeight: "800", marginBottom: "8px" }}>Privacy Policy</h1>
      <p style={{ color: "var(--muted)", fontSize: "14px", marginBottom: "48px" }}>Last Updated: May 12, 2026</p>

      <div className="legal-body">

        <p>FinalPingApp ("we," "us," or "our") is committed to protecting your privacy. This Privacy Policy explains what information we collect when you use FinalPing, how we use and share it, how long we keep it, and the rights available to you. By using FinalPing, you agree to the practices described in this policy.</p>

        <h2>1. Who We Are</h2>
        <p>FinalPingApp is a sole proprietorship operating the FinalPing aircraft tracking desktop application and associated web services at finalpingapp.com. For privacy inquiries, you may contact us at <a href="mailto:aircraftalerts@finalpingapp.com">aircraftalerts@finalpingapp.com</a>.</p>

        <h2>2. Information We Collect</h2>
        <p><strong>Account Information.</strong> When you create an account or activate FinalPing, we collect your email address, a hashed password, license key, and the date and time of activation. If you enable two-factor authentication, we store your 2FA method preference and a hashed verification token.</p>
        <p><strong>Configuration Data.</strong> To deliver the tracking service, we store: aircraft tail numbers and ICAO24 hex codes you choose to monitor, your tracking location coordinates and airport code, detection radius and polling interval settings, quiet hours preferences, alert distance thresholds, webhook URLs (Discord, Slack, Teams, custom HTTPS endpoints), and Twilio SMS credentials you optionally provide.</p>
        <p><strong>Alert and Log Data.</strong> We store a history of alert notifications generated by your account, including timestamp, aircraft identifier, alert type, integration type, delivery status, and the alert message. This data is used to populate your alert history dashboard and export features.</p>
        <p><strong>Technical and Device Data.</strong> We may collect application version numbers, general error and diagnostic logs, and aggregated usage analytics (via PostHog) to improve the Software. PostHog analytics data is anonymized and does not identify you personally.</p>
        <p><strong>Support Communications.</strong> If you contact us through the contact form or by email, we retain the content of those communications to respond to your request.</p>

        <h2>3. Information We Do Not Collect</h2>
        <ul>
          <li>Your name or physical address</li>
          <li>Payment card numbers or banking information (processed by Stripe; we never see your card details)</li>
          <li>Browsing history or behavior outside the FinalPing application and website</li>
          <li>The content of messages delivered to your configured webhooks or SMS integrations</li>
          <li>Real-time location data about you personally</li>
          <li>Any data from aircraft beyond what you explicitly configure</li>
        </ul>

        <h2>4. How We Use Your Information</h2>
        <p>We use the information we collect to:</p>
        <ul>
          <li>Authenticate your license and provide access to the Software</li>
          <li>Sync your configuration across authorized devices</li>
          <li>Deliver aircraft proximity notifications to your configured integrations</li>
          <li>Maintain your alert history and make it accessible through your account dashboard</li>
          <li>Send transactional emails, including license delivery, renewal confirmations, and account security notices</li>
          <li>Respond to support requests and contact form submissions</li>
          <li>Detect and prevent fraud, abuse, and unauthorized access</li>
          <li>Improve, maintain, and develop the Software and related services</li>
          <li>Comply with legal obligations</li>
        </ul>
        <p>We do not sell, rent, or share your personal information with third parties for marketing or advertising purposes.</p>

        <h2>5. Legal Basis for Processing (GDPR)</h2>
        <p>If you are located in the European Economic Area (EEA) or United Kingdom, our legal basis for processing your personal data is:</p>
        <ul>
          <li><strong>Performance of a contract:</strong> Processing necessary to deliver the Software and services you purchased</li>
          <li><strong>Legitimate interests:</strong> Fraud prevention, security, product improvement, and support communications</li>
          <li><strong>Legal obligation:</strong> Compliance with applicable laws and regulations</li>
          <li><strong>Consent:</strong> Where you have given explicit consent (for example, optional analytics participation)</li>
        </ul>

        <h2>6. Third-Party Services</h2>
        <p><strong>ADS-B Data.</strong> FinalPing uses publicly available ADS-B flight data from adsb.lol. Your tracking location coordinates are transmitted to this provider as part of API requests to retrieve nearby aircraft data. adsb.lol operates independently and has its own privacy policy.</p>
        <p><strong>Stripe.</strong> License purchases and subscription billing are processed by Stripe, Inc. FinalPingApp does not store payment card information. Stripe acts as an independent data controller for payment data. Stripe's privacy policy is available at <a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">stripe.com/privacy</a>.</p>
        <p><strong>Resend.</strong> We use Resend to send transactional and account-related emails. Only your email address and the content of the specific email are shared with Resend. Resend's privacy policy is available at <a href="https://resend.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">resend.com/legal/privacy-policy</a>.</p>
        <p><strong>Railway.</strong> Our backend infrastructure is hosted on Railway (railway.app). Your configuration and account data are stored on Railway servers. Railway's privacy policy is available at <a href="https://railway.app/legal/privacy" target="_blank" rel="noopener noreferrer">railway.app/legal/privacy</a>.</p>
        <p><strong>PostHog.</strong> We use PostHog for anonymized product analytics on the FinalPing website. PostHog does not receive personally identifiable information. PostHog's privacy policy is available at <a href="https://posthog.com/privacy" target="_blank" rel="noopener noreferrer">posthog.com/privacy</a>.</p>
        <p><strong>Twilio.</strong> If you configure SMS alerts, Twilio processes and delivers SMS messages to the phone number you provide. FinalPingApp does not store the content of SMS messages after delivery. Twilio's privacy policy is available at <a href="https://www.twilio.com/legal/privacy" target="_blank" rel="noopener noreferrer">twilio.com/legal/privacy</a>.</p>
        <p><strong>Webhooks and Integrations.</strong> When an alert is triggered, FinalPing sends a notification payload to the webhook URL(s) you configure (Discord, Slack, Teams, custom HTTPS). FinalPingApp does not store the content of webhook deliveries after transmission. You are responsible for the privacy and security of any endpoint you configure.</p>

        <h2>7. Cookies and Tracking</h2>
        <p>The FinalPing website uses cookies and similar technologies to maintain your authenticated session, remember your preferences, and support anonymized analytics (PostHog). You may control cookies through your browser settings. Disabling session cookies will prevent you from logging in to your account dashboard.</p>

        <h2>8. Data Storage and Security</h2>
        <p>Your account and configuration data are stored on servers hosted by Railway. Authentication tokens on your device are stored in encrypted application storage. We implement industry-standard technical and organizational measures to protect your data against unauthorized access, alteration, disclosure, or destruction, including encrypted connections (HTTPS/TLS), hashed password storage, and access controls.</p>
        <p>No method of transmission over the internet or electronic storage is 100% secure. While we take reasonable precautions, we cannot guarantee absolute security.</p>

        <h2>9. Data Retention</h2>
        <p>We retain your account and configuration data for as long as your account remains active or as needed to provide the service. Alert history logs are retained for up to 12 months. If you request deletion of your account, we will delete or anonymize your personal data within 30 days, except where retention is required by law (for example, financial records related to billing may be retained for up to 7 years).</p>

        <h2>10. Your Rights</h2>
        <p>Depending on your location, you may have the following rights regarding your personal data:</p>
        <ul>
          <li><strong>Access:</strong> Request a copy of the personal data we hold about you</li>
          <li><strong>Correction:</strong> Request correction of inaccurate or incomplete data</li>
          <li><strong>Deletion:</strong> Request deletion of your personal data ("right to be forgotten")</li>
          <li><strong>Restriction:</strong> Request that we restrict processing of your data</li>
          <li><strong>Portability:</strong> Receive your data in a structured, machine-readable format</li>
          <li><strong>Objection:</strong> Object to processing based on legitimate interests</li>
          <li><strong>Withdrawal of consent:</strong> Withdraw consent at any time where processing is based on consent</li>
        </ul>
        <p>To exercise any of these rights, contact us at <a href="mailto:aircraftalerts@finalpingapp.com">aircraftalerts@finalpingapp.com</a>. We will respond within 30 days. We may need to verify your identity before fulfilling a request.</p>

        <h2>11. California Consumer Privacy Act (CCPA)</h2>
        <p>If you are a California resident, you have the right to know what personal information we collect, use, and disclose; the right to request deletion of your personal information; and the right not to be discriminated against for exercising these rights. FinalPingApp does not sell personal information as defined by the CCPA. To submit a CCPA request, contact us at <a href="mailto:aircraftalerts@finalpingapp.com">aircraftalerts@finalpingapp.com</a>.</p>

        <h2>12. International Data Transfers</h2>
        <p>FinalPingApp operates primarily in the United States. If you are accessing the Software from outside the United States, your data may be transferred to and processed in the United States, where data protection laws may differ from those in your country. By using the Software, you consent to this transfer. We implement appropriate safeguards, including standard contractual clauses where required, to protect data transferred internationally.</p>

        <h2>13. Children's Privacy</h2>
        <p>FinalPing is not directed at children under the age of 13 (or 16 in the EEA). We do not knowingly collect personal information from children under these ages. If we become aware that we have inadvertently collected such information, we will promptly delete it. If you believe we have collected information from a child, please contact us immediately at <a href="mailto:aircraftalerts@finalpingapp.com">aircraftalerts@finalpingapp.com</a>.</p>

        <h2>14. Changes to This Policy</h2>
        <p>We may update this Privacy Policy from time to time to reflect changes in our practices, legal requirements, or the Software. We will notify you of significant changes by updating the "Last Updated" date at the top of this policy and, where appropriate, by sending an email notification. Your continued use of the Software after changes are posted constitutes your acceptance of the revised policy.</p>

        <h2>15. Contact Us</h2>
        <p>If you have any questions, concerns, or requests regarding this Privacy Policy or your personal data, please contact us at:</p>
        <p>
          <strong>FinalPingApp</strong><br />
          Email: <a href="mailto:aircraftalerts@finalpingapp.com">aircraftalerts@finalpingapp.com</a><br />
          Website: <a href="https://finalpingapp.com/contact">finalpingapp.com/contact</a>
        </p>

      </div>

    </div>
  );
}
